name: CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  test:
    name: UnitTest
    runs-on: macOS-latest
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=15.0,name=iPhone 13 Pro Max']
        xcode: ['/Applications/Xcode_13.1.app/Contents/Developer']

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run test
        run: xcodebuild test -workspace QRScanner.xcworkspace -scheme UnitTests -destination "${destination}"
        env:
          destination: ${{ matrix.destination }}
          DEVELOPER_DIR: ${{ matrix.xcode }}
