name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: UnitTest
    runs-on: macOS-latest
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=18.0,name=iPhone 16 Pro Max']

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Select latest Xcode
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
      - name: Run unit tests
        run: xcodebuild test -workspace QRScanner.xcworkspace -scheme UnitTests -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
        env:
          destination: ${{ matrix.destination }}
